// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj-LZ-11PLUm6MPlCotNe8-owRdaZB8fY',
    appId: '1:48100836768:web:9bcaac127874c56434d0c5',
    messagingSenderId: '48100836768',
    projectId: 'hackathon-nfc-bc233',
    authDomain: 'hackathon-nfc-bc233.firebaseapp.com',
    storageBucket: 'hackathon-nfc-bc233.firebasestorage.app',
    measurementId: 'G-LNKYDB22T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-jS8pX3QrT2y0HqLS_QGv0yA0Y-m6Ypo',
    appId: '1:48100836768:android:3d7d1aa969f43f6234d0c5',
    messagingSenderId: '48100836768',
    projectId: 'hackathon-nfc-bc233',
    storageBucket: 'hackathon-nfc-bc233.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK0q9BA05OoTos792yX55PjVhu3qF6Fpk',
    appId: '1:48100836768:ios:ea41c0d70221c58f34d0c5',
    messagingSenderId: '48100836768',
    projectId: 'hackathon-nfc-bc233',
    storageBucket: 'hackathon-nfc-bc233.firebasestorage.app',
    iosBundleId: 'com.example.hackathonNfc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK0q9BA05OoTos792yX55PjVhu3qF6Fpk',
    appId: '1:48100836768:ios:ea41c0d70221c58f34d0c5',
    messagingSenderId: '48100836768',
    projectId: 'hackathon-nfc-bc233',
    storageBucket: 'hackathon-nfc-bc233.firebasestorage.app',
    iosBundleId: 'com.example.hackathonNfc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj-LZ-11PLUm6MPlCotNe8-owRdaZB8fY',
    appId: '1:48100836768:web:d8fc6a1663201dfc34d0c5',
    messagingSenderId: '48100836768',
    projectId: 'hackathon-nfc-bc233',
    authDomain: 'hackathon-nfc-bc233.firebaseapp.com',
    storageBucket: 'hackathon-nfc-bc233.firebasestorage.app',
    measurementId: 'G-V63K9YFTXL',
  );

}